# Generated by Django 3.0.2 on 2020-03-28 05:19

from django.db import migrations, models
import tweet.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20200324_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=140, validators=[tweet.utils.validateText]),
        ),
    ]
