# Generated by Django 3.0.2 on 2020-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('tweet', '0004_auto_20200328_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='tweets', to='hashtag.Hashtag'),
        ),
    ]
