# Generated by Django 3.0.2 on 2020-04-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('tweet', '0005_tweet_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tweets', to='hashtag.Hashtag'),
        ),
    ]
