# Generated by Django 3.0.2 on 2020-04-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('tweet', '0006_auto_20200403_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='hashtag.Hashtag'),
        ),
    ]
