# Generated by Django 3.0.2 on 2020-04-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_auto_20200403_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parentTweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parenttweets', to='tweet.Tweet'),
        ),
    ]
